#!/bin/bash
set -euo pipefail

BUILDER_IMAGE=rpi-image-builder
# Build the image builder image
docker image build --rm --force-rm --tag ${BUILDER_IMAGE} image-builder

# Capture host env variables
envfile=$(mktemp $(pwd)/.envfile.XXXXXX)
export -p | grep -v "DISPLAY\|HOME\|HOST=\|LS_COLORS\|PATH\|PERL\|PWD\|SHELL\|SHLVL\|SSH\|TERM\|TMPDIR\|USER" > ${envfile}
trap 'rm -f ${envfile}' EXIT

# Run the image builder
docker container run --rm -it --privileged \
                     --mount type=bind,src=${envfile},dst=/tmp/envfile \
                     --mount type=bind,src=$(pwd),dst=/builder \
                     --mount type=bind,src=/var/run/docker.sock,dst=/var/run/docker.sock \
                     --workdir /builder \
                     ${BUILDER_IMAGE} \
                     image-builder/mount-image "$1"
rm ${envfile}
