#!/bin/bash
set -euo pipefail

BUILDER_IMAGE=$(cat .image-name)

# Build the image builder image
docker image build --rm --force-rm --tag ${BUILDER_IMAGE} image-builder

# Run the image builder
docker container run --rm -it --privileged \
                     --name rpi-explore-image-$(uuidgen) \
                     --mount type=bind,src=$(pwd),dst=/builder \
                     --mount type=bind,src=/var/run/docker.sock,dst=/var/run/docker.sock \
                     --workdir /builder \
                     ${BUILDER_IMAGE} \
                     image-builder/mount-image "$1"
