#!/bin/bash
set -euo pipefail

if [[ -z "${CHROOT:-}" ]]; then
    echo "CHROOT is not defined"
    exit 1
fi

# Create a blank cloud-init user-data file. Other hooks may add to this file later
echo "Initializing /boot/firmware/user-data"
echo "#cloud-config" > "${CHROOT}"/boot/firmware/user-data
