#!/bin/bash
set -euo pipefail

if [[ -z "${CHROOT:-}" ]]; then
    echo "CHROOT is not defined"
    exit 1
fi

sed -e 's/PasswordAuthentication no/PasswordAuthentication yes/' -i "${CHROOT}"/etc/ssh/sshd_config
