#!/bin/bash
set -euo pipefail

export APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1
export DEBIAN_FRONTEND=noninteractive

add-apt-repository --yes ppa:ubuntu-pi-flavour-makers/ppa

apt-get update
apt-get dist-upgrade --yes

# Install useful packages
apt-get install --yes \
    arptables \
    avahi-daemon \
    curl \
    iperf3 \
    iptables \
    jq \
    ebtables \
    libraspberrypi-bin \
    linux-firmware-raspi2 \
    net-tools \
    nfs-common \
    rpi-eeprom \
    sysbench \
    tree \
    vim
