#!/bin/bash
set -euo pipefail

export APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1
export DEBIAN_FRONTEND=noninteractive

apt-get update

# Prerequisites
apt-get install --yes \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
	lsb-release \
    software-properties-common

# Add docker repo
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
echo "deb [arch=arm64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list

apt-get update

# Install docker
apt-get install --yes docker-ce docker-ce-cli containerd.io

# Docker configuration
mkdir -p /etc/docker
cat << EOF > /etc/docker/daemon.json
{
	"exec-opts": ["native.cgroupdriver=systemd"],
	"log-driver": "json-file",
	"log-opts": {
		"max-size": "100m"
	},
	"storage-driver": "overlay2"
}
EOF
