#!/bin/bash
set -euo pipefail

HOSTNAME=${HOSTNAME:-}
IP=${IP:-}

# Set a hostname
if [[ -z ${HOSTNAME} ]]; then
    HOSTNAME=$(cat /dev/urandom | tr -dc [:alnum:] | head -c8 || true)
    echo "Setting random hostname ${HOSTNAME}"
else
    echo "Setting hostname ${HOSTNAME}"
fi
echo "hostname: ${HOSTNAME}" >> /boot/firmware/user-data

# Set an IP for eth0
if [[ -n ${IP} ]]; then 
    echo "Setting static IP ${IP}"
    cat config-hooks/net-static-template.yaml | envsubst > /boot/firmware/network-config
fi
